### ISSUE TITLE
undefined method `messages' for #<IOError: closed stream> [NoMethodError]

### ISSUE THREAD

**Issue by DenisKlimek** [ytti/oxidized#3583]
- [X ] I have read and understood [docs/Issues.md](https://github.com/ytti/oxidized/blob/master/docs/Issues.md).

**Describe the bug**
Hello,

after an forced upgrade from Ubuntu 22.04 to 24.04 together with Oxidized 0.28.0 to latest 0.34.1 we are facing an issue with two xos-based devices. The SSH connection is successfully, oxidized is sending his commands i.e. show configuration, show diag... show policy etc pp and logsout via "exit". After step this job crashes with attached failure message. Only 2 of 145 are showing this behaviour after upgrading and I can not see any difference between those.

**To Reproduce**
1. Configure 'extreme xos device into router.db'
2. Use model 'xos'
3. Run 'ssh'

**Expected behavior**
Saving configuration into git and that's it. SSH connection is possible and user disconnects from devices successfully.

**Configuration**
```
If applicable, publish your configuration.
```

**Logs**
```
2025-07-22 06:54:18 UTC
undefined method `messages' for #<IOError: closed stream> [NoMethodError]
--------------------------------------------------
/var/lib/gems/3.2.0/gems/oxidized-0.34.1/lib/oxidized/input/ssh.rb:84:in `rescue in disconnect'
/var/lib/gems/3.2.0/gems/oxidized-0.34.1/lib/oxidized/input/ssh.rb:82:in `disconnect'
/var/lib/gems/3.2.0/gems/oxidized-0.34.1/lib/oxidized/input/cli.rb:15:in `get'
/var/lib/gems/3.2.0/gems/oxidized-0.34.1/lib/oxidized/node.rb:75:in `run_input'
/var/lib/gems/3.2.0/gems/oxidized-0.34.1/lib/oxidized/node.rb:50:in `block in run'
/var/lib/gems/3.2.0/gems/oxidized-0.34.1/lib/oxidized/node.rb:44:in `each'
/var/lib/gems/3.2.0/gems/oxidized-0.34.1/lib/oxidized/node.rb:44:in `run'
/var/lib/gems/3.2.0/gems/oxidized-0.34.1/lib/oxidized/job.rb:13:in `block in initialize'
```

**Running environment (please complete the following information):**

- OS: Ubuntu 24.04
- oxidized version: 0.34.1
- oxidized-web version: 0.17.0
- Manufacturer model an software version: 16.2.4.5-patch1-5
- oxidized model name: xos

**Additional context**

**Comment by ytti** [comment]
The bug is introduced in https://github.com/ytti/oxidized/commit/b7618cd25450eff875b1a96756403fe04a89618a

You can fix it by changing the plural e.messages into singular e.message.
