### ISSUE TITLE
"junos-set" backup isn't working anymore since upgrading from 0.28.0 to 0.29.1

### ISSUE THREAD

**Issue by davromaniak** [ytti/oxidized#2868]
Hey.

I just upgraded to Oxidized 0.29.1 (from 0.28.0) on a RockyLinux 8.6 and I'm facing an issue with the junos-set type of backup.

It complitely crashes Oxidized, here's the crash log. The string is containing the whole config in the "junos set" format.

```
--------------------------------------------------
2023-07-13 18:28:53 UTC
undefined method `name' for "set version 17.3R3-S1.5\nset groups...":String [NoMethodError]
--------------------------------------------------
/usr/local/share/gems/gems/oxidized-0.29.1/lib/oxidized/output/git.rb:47:in `block (2 levels) in store'
/usr/local/share/gems/gems/oxidized-0.29.1/lib/oxidized/output/git.rb:46:in `each'
/usr/local/share/gems/gems/oxidized-0.29.1/lib/oxidized/output/git.rb:46:in `block in store'
/usr/local/share/gems/gems/oxidized-0.29.1/lib/oxidized/output/git.rb:43:in `each'
/usr/local/share/gems/gems/oxidized-0.29.1/lib/oxidized/output/git.rb:43:in `store'
/usr/local/share/gems/gems/oxidized-0.29.1/lib/oxidized/worker.rb:65:in `process_success'
/usr/local/share/gems/gems/oxidized-0.29.1/lib/oxidized/worker.rb:47:in `process'
/usr/local/share/gems/gems/oxidized-0.29.1/lib/oxidized/worker.rb:16:in `block in work'
/usr/local/share/gems/gems/oxidized-0.29.1/lib/oxidized/worker.rb:16:in `each'
/usr/local/share/gems/gems/oxidized-0.29.1/lib/oxidized/worker.rb:16:in `work'
/usr/local/share/gems/gems/oxidized-0.29.1/lib/oxidized/core.rb:36:in `run'
/usr/local/share/gems/gems/oxidized-0.29.1/lib/oxidized/core.rb:29:in `initialize'
/usr/local/share/gems/gems/oxidized-0.29.1/lib/oxidized/core.rb:4:in `new'
/usr/local/share/gems/gems/oxidized-0.29.1/lib/oxidized/core.rb:4:in `new'
/usr/local/share/gems/gems/oxidized-0.29.1/lib/oxidized/cli.rb:13:in `run'
/usr/local/share/gems/gems/oxidized-0.29.1/bin/oxidized:8:in `<top (required)>'
/usr/local/bin/oxidized:23:in `load'
/usr/local/bin/oxidized:23:in `<main>'
--------------------------------------------------
```

Here the local model : 
```
$ cat .config/oxidized/model/junos.rb
require 'oxidized/model/junos.rb'

class JunOS < Oxidized::Model
    using Refinements

    cmd 'show configuration | display set' do |cfg|
        cfg.type = "junos-set"
        cfg.name = "set"
        cfg
    end
end
```

For now, I removed this model file and Oxidized runs smoothly.

Here's the git portion of the config file : 

```
output:
  default: git
  git:
    single_repo: true
    user: Oxidized
    repo: "/opt/oxidized/devices"
    type_as_directory: true
```

I'm a bit lost on what/where to check for debug.

Don't hesitate to ask me for more info.

Thanks.

**Comment by davromaniak** [comment]
Hi.

Well, after a good night of sleep, I found the issue.

I needed to apply this commit : https://github.com/ytti/oxidized/commit/440e7bcece3070541aac7ba033f037e6455705a6

Which adds a `using Refinements` to the git output.

I hope this issue will help anybody with this issue while waiting for a new release.

Thanks
