### ISSUE TITLE
Comware issues with cut_both in 0.29.0

### ISSUE THREAD

**Issue by neilschelly** [ytti/oxidized#2749]
I just upgrade to 0.29.0 (running in the containers from DockerHub), and I'm running into a new error only on my HP/Comware switches. I haven't yet investigated what's going on, but I'll attempt working on a fix soon so that I don't have to downgrade back to 0.28.0.

```
E, [2023-04-13T17:53:00.650207 #1] ERROR -- : IPADDRESS raised NoMethodError with msg "undefined method `cut_both' for 

"display version
HPE Comware Platform Software
Comware Software, Version 5.20.99, Release 5501P36
<SNIP>

<SWITCHNAME>":String"
```

To be explicit, this is happening on the following switches:
* HPE FF 5700-40XG-2QSFP+ switch, running Comware Software, Version 7.1.045, Release 2432P06
* A5500-48G-4SFP HI JG312A switch, running Comware Software, Version 5.20.99, Release 5501P36
* HPE 5820X-24XG-SFP+ switch, running Comware Software, Version 5.20.105, Release 1810P16
* HP A5500-24G-4SFP HI switch, running Comware Software, Version 5.20.99, Release 5501P36

All these switches worked before on 0.28.0, and all my other devices are working fine with 0.29.0. That includes FortiOS, EdgeOS, and JunOS devices, but it's possible that none of those use the cut_both() function. I have been looking at the changed files between the releases, and nothing obviously jumps out at me to explain why this behavior has changed/broken/etc.

**Comment by ytti** [comment]
Are you sure you were running 0.28.0, I think you were running earlier.


I believe this was broken in https://github.com/ytti/oxidized/commit/9db0c31f5656d1b689fd6261079730366f15591c

When we enter the block, the object is Oxidized::String, and we can use the methods it defines. But gsub here returns String, and we are attempting to use Oxidized::String method for String, which won't work.

We have few options

1. Recast the String to Oxidized::String before using cut_both
2. Monkey patch String to include all Oxidized::String methods, so that we don't care which one it is
3. Refine String to include all Oxidied:String methods

2. is bit dangerous as then all libraries we use, and all libraries those libraries use will get the monkey patched String. 3. will prevent this. I wanted to do 3. originally, but at the time refinements was very new feature not available in default ruby in redhat/debian/ubuntu. This has changed, so maybe #3 is right solution for the problem.

**Comment by neilschelly** [comment]
I am sure I was using something close to 0.28.0 at least since that's what the UI reported. I expect I was using the code at https://github.com/neilschelly/oxidized/tree/master because that's where I'd merged my improvements for TrueNAS things that got incorporated into 0.29.0.

That said, this sounds like exactly the problem I was seeing. I tried building the code in aschaber1:2749-comware-issues-with-cut_both-in-0290, but ran into a full crash pulling configs from the first device it tried (JunOS). I'll comment on that PR.

**Comment by neilschelly** [comment]
The bugfix at https://github.com/ytti/oxidized/pull/2750 is working as intended now.
