### ISSUE TITLE
Semantic logger missing in shim model

### ISSUE THREAD

**Issue by rvandepu** [ytti/oxidized#3617]
Hi,

https://github.com/ytti/oxidized/blob/218b4acbaab3efa3e2c4a44d8033fadfd277b12d/lib/oxidized/model/timos.rb#L8

This shim model is broken since commit https://github.com/ytti/oxidized/commit/25d060f5b6a2e47571c3eb01ae92abdc29dedc0e. 

```
2025-08-21 12:49:57 UTC
undefined local variable or method `logger' for main:Object [NameError]
--------------------------------------------------
/var/lib/gems/3.2.0/gems/oxidized-0.34.3/lib/oxidized/model/timos.rb:8:in `<top (required)>'
<internal:/usr/lib/ruby/vendor_ruby/rubygems/core_ext/kernel_require.rb>:86:in `require'
<internal:/usr/lib/ruby/vendor_ruby/rubygems/core_ext/kernel_require.rb>:86:in `require'
/var/lib/gems/3.2.0/gems/oxidized-0.34.3/lib/oxidized/manager.rb:9:in `load'
/var/lib/gems/3.2.0/gems/oxidized-0.34.3/lib/oxidized/manager.rb:62:in `loader'
/var/lib/gems/3.2.0/gems/oxidized-0.34.3/lib/oxidized/manager.rb:49:in `add_model'
/var/lib/gems/3.2.0/gems/oxidized-0.34.3/lib/oxidized/node.rb:193:in `resolve_model'
/var/lib/gems/3.2.0/gems/oxidized-0.34.3/lib/oxidized/node.rb:25:in `initialize'
/var/lib/gems/3.2.0/gems/oxidized-0.34.3/lib/oxidized/nodes.rb:24:in `new'
/var/lib/gems/3.2.0/gems/oxidized-0.34.3/lib/oxidized/nodes.rb:24:in `block (2 levels) in load'
/var/lib/gems/3.2.0/gems/oxidized-0.34.3/lib/oxidized/nodes.rb:19:in `each'
/var/lib/gems/3.2.0/gems/oxidized-0.34.3/lib/oxidized/nodes.rb:19:in `block in load'
/var/lib/gems/3.2.0/gems/oxidized-0.34.3/lib/oxidized/nodes.rb:149:in `synchronize'
/var/lib/gems/3.2.0/gems/oxidized-0.34.3/lib/oxidized/nodes.rb:149:in `with_lock'
/var/lib/gems/3.2.0/gems/oxidized-0.34.3/lib/oxidized/nodes.rb:13:in `load'
/var/lib/gems/3.2.0/gems/oxidized-0.34.3/lib/oxidized/nodes.rb:144:in `initialize'
/var/lib/gems/3.2.0/gems/oxidized-0.34.3/lib/oxidized/core.rb:16:in `new'
/var/lib/gems/3.2.0/gems/oxidized-0.34.3/lib/oxidized/core.rb:16:in `initialize'
/var/lib/gems/3.2.0/gems/oxidized-0.34.3/lib/oxidized/core.rb:4:in `new'
/var/lib/gems/3.2.0/gems/oxidized-0.34.3/lib/oxidized/core.rb:4:in `new'
/var/lib/gems/3.2.0/gems/oxidized-0.34.3/lib/oxidized/cli.rb:17:in `run'
/var/lib/gems/3.2.0/gems/oxidized-0.34.3/bin/oxidized:5:in `<top (required)>'
/usr/local/bin/oxidized:25:in `load'
/usr/local/bin/oxidized:25:in `<main>'
```

My Ruby knowledge is very limited, but I believe it occurs due to the fact that this model does not reference the Oxidixed::Model class, which imports the new semantic logger. Anyway, referring to `sros` as model instead of `timos` does the trick for now. But this should probably be resolved.

Thanks.

**Comment by ytti** [comment]
Maybe:

```ruby
class TiMOS < SROS
  logger.warn ...
end
```

**Comment by robertcheramy** [comment]
The timos.rb model has been deprecated for seven years, so I think it is safe to remove it now.
